// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type MorningPoll struct {
	ID       int64
	FileName sql.NullString
}

type MorningPollsOption struct {
	ID            int64
	MorningPollID sql.NullInt64
	OptionTetxt   sql.NullString
	Foreign       interface{}
}

type SendedPoll struct {
	ID       int64
	PollTgID sql.NullString
}
