// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddSendedVote(ctx context.Context, pollTgID sql.NullString) error
	GetLastIdMorningPoll(ctx context.Context) (int64, error)
	GetLastSendedPoll(ctx context.Context) (SendedPoll, error)
	GetMorningPollById(ctx context.Context, id int64) (MorningPoll, error)
	GetOpionsForPoll(ctx context.Context, morningPollID sql.NullInt64) ([]MorningPollsOption, error)
}

var _ Querier = (*Queries)(nil)
