name: Lint and Test
run-name: Linting and testing
on: [push]

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: go install
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: go install
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
      - name: install dependencies
        run: |
          go mod tidy
          go mod download
      - name: build
        run: |
          go build -o main ./cmd/monkeyMorning/main.go
      - name: test
        run: |
          go test ./...
